/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.ConexaoSQL;
import Padroes.FormatacaoDeCampos;
import Padroes.Mensagens_Prontas;
import Padroes.Validacoes;
import Padroes.sql_padroes;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author samuel
 */
public class AltSenha extends javax.swing.JFrame {
        
    private ConexaoSQL          db;
    private DefaultTableModel   dtm;
    private sql_padroes         sqlPadroes;
    private Mensagens_Prontas   msg;
    private FormatacaoDeCampos  formatar;
    private Validacoes          validar;
    private int                 previlegios;
    private String              nomeUsuario;
    private boolean             isOpened;
    
  
    //CONFIGURA O NOME DO FRAME
    private void TituloAplicacao (String nomeUsuario){
        this.setTitle("PSC LAVA JATO - Usuário logado: "+nomeUsuario);
    }

    // DIMENCIONA O TAMANHO DE ALGUNS COMPONENTES
    private void setDimensionarCampos (){
        //DIMENCIONA A IMAGEM DE FUNDO DOS JTEXTFIELDS
        this.formatar.setDimencionarIcone(440, 40 ,"/Icons/fundoTextField.png", fundoRepetirSenha); 
        this.formatar.setDimencionarIcone(440, 40 ,"/Icons/fundoTextField.png", fundoSenhaAtual); 
        this.formatar.setDimencionarIcone(440, 40 ,"/Icons/fundoTextField.png", fundoNovaSenha); 
     
        // DIMENCIONA A BORDA DO MENU LATERAL
        this.formatar.setDimencionarIcone(60, this.getHeight(),"/Icons/bordaMenu.png", imgBorda); 
    }
    
    public AltSenha(String nome) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        // INSTANCIA ALGUMAS CLASSES QUE SERÃO UTILIZADAS
        this.msg        = new Mensagens_Prontas();
        this.formatar   = new FormatacaoDeCampos();
        this.sqlPadroes = new sql_padroes();
        this.db         = new ConexaoSQL();
        this.validar    = new Validacoes();
        
        // NOMEIA O TÍTULO DA PÁGINA
        this.nomeUsuario = nome;
        this.TituloAplicacao(this.nomeUsuario);
        
        // PEGA O TIPO DE PREVILÉGIO DA PESSOA (USUÁRIO X OPERADOR)
        this.previlegios = Integer.parseInt(sqlPadroes.getValue("funcionario", "IsAdministrador", this.nomeUsuario));
        
        // PERSONALIZA O BOTÃO MENU
        btnMenu.setOpaque(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setBorderPainted(false);
        
        // DIMENCIONA O TAMANHO DE ALGUNS COMPONENTES
        this.setDimensionarCampos();
        
        // BOOLEAN QUE MARCA SE A BORDA DO MENU ESTÁ ABERTA OU NÃO
        this.isOpened = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        iconTitulo = new javax.swing.JLabel();
        sepTitulo = new javax.swing.JSeparator();
        pnLateralMenu = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        imgBorda = new javax.swing.JLabel();
        pnlLateral = new javax.swing.JPanel();
        txtLogo = new javax.swing.JLabel();
        btnAlt = new javax.swing.JButton();
        sepLogo = new javax.swing.JSeparator();
        txtTituloEmpresa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlCampos = new javax.swing.JPanel();
        txtSenhaAtual = new javax.swing.JLabel();
        pfSenhaAtual = new javax.swing.JPasswordField();
        fundoSenhaAtual = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JLabel();
        pfNovaSenha = new javax.swing.JPasswordField();
        fundoNovaSenha = new javax.swing.JLabel();
        txtRepetirSenha = new javax.swing.JLabel();
        pfSenhaRepetida = new javax.swing.JPasswordField();
        fundoRepetirSenha = new javax.swing.JLabel();
        sepCampos = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(79, 148, 205));

        titulo.setFont(new java.awt.Font("MV Boli", 1, 30)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("ALTERAR SENHA");

        iconTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconEdit.png"))); // NOI18N

        pnLateralMenu.setBackground(new java.awt.Color(79, 148, 205));
        pnLateralMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconMenu.png"))); // NOI18N
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        pnLateralMenu.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));

        imgBorda.setBackground(new java.awt.Color(79, 148, 205));
        imgBorda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bordaMenu.png"))); // NOI18N
        imgBorda.setToolTipText("");
        pnLateralMenu.add(imgBorda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlLateral.setBackground(new java.awt.Color(17, 32, 63));
        pnlLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LOGO.png"))); // NOI18N
        pnlLateral.add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 217, -1));

        btnAlt.setBackground(new java.awt.Color(255, 255, 255));
        btnAlt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconVerificado.png"))); // NOI18N
        btnAlt.setText("ALTERAR");
        btnAlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAltMouseExited(evt);
            }
        });
        pnlLateral.add(btnAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 256, 240, -1));

        sepLogo.setBackground(new java.awt.Color(255, 255, 255));
        sepLogo.setForeground(new java.awt.Color(255, 255, 255));
        pnlLateral.add(sepLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 240, 10));

        txtTituloEmpresa.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtTituloEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloEmpresa.setText("PSC LAVA-JATO");
        pnlLateral.add(txtTituloEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, 217, -1));

        jPanel1.setBackground(new java.awt.Color(79, 148, 205));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlCampos.setBackground(new java.awt.Color(79, 148, 205));
        pnlCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSenhaAtual.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtSenhaAtual.setForeground(new java.awt.Color(255, 255, 255));
        txtSenhaAtual.setText("SENHA ATUAL");
        pnlCampos.add(txtSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 200, -1));

        pfSenhaAtual.setBackground(new java.awt.Color(255, 255, 255));
        pfSenhaAtual.setForeground(new java.awt.Color(0, 0, 0));
        pfSenhaAtual.setBorder(null);
        pnlCampos.add(pfSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, 20));

        fundoSenhaAtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fundoTextField.png"))); // NOI18N
        fundoSenhaAtual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundoSenhaAtualMouseClicked(evt);
            }
        });
        pnlCampos.add(fundoSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 40));

        txtNovaSenha.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtNovaSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtNovaSenha.setText("NOVA SENHA");
        pnlCampos.add(txtNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        pfNovaSenha.setBackground(new java.awt.Color(255, 255, 255));
        pfNovaSenha.setForeground(new java.awt.Color(0, 0, 0));
        pfNovaSenha.setBorder(null);
        pnlCampos.add(pfNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 420, 20));

        fundoNovaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fundoTextField.png"))); // NOI18N
        fundoNovaSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundoNovaSenhaMouseClicked(evt);
            }
        });
        pnlCampos.add(fundoNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 440, 40));

        txtRepetirSenha.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtRepetirSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtRepetirSenha.setText("REPITA A NOVA SENHA");
        pnlCampos.add(txtRepetirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        pfSenhaRepetida.setBackground(new java.awt.Color(255, 255, 255));
        pfSenhaRepetida.setForeground(new java.awt.Color(0, 0, 0));
        pfSenhaRepetida.setBorder(null);
        pnlCampos.add(pfSenhaRepetida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 420, 20));

        fundoRepetirSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fundoTextField.png"))); // NOI18N
        fundoRepetirSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundoRepetirSenhaMouseClicked(evt);
            }
        });
        pnlCampos.add(fundoRepetirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 440, 40));
        pnlCampos.add(sepCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 420, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(sepTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                                .addGap(80, 80, 80))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(iconTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titulo)
                                .addGap(367, 367, 367))))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnLateralMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(sepTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnLateralMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // FUNÇÃO QUE FECHA E ABRE O MENU LATERAL...
        if(this.isOpened == true) {
            pnlLateral.setVisible(false);
            this.isOpened = false;}
        
        else {
            pnlLateral.setVisible(true);
            this.isOpened = true;}
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnAltMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltMouseExited
        btnAlt.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnAltMouseExited

    private void btnAltMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltMouseEntered
        btnAlt.setBackground(new java.awt.Color(152 ,251, 152));
    }//GEN-LAST:event_btnAltMouseEntered

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconMenuSelect.png")));

    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconMenu.png")));

    }//GEN-LAST:event_btnMenuMouseExited

    private void fundoSenhaAtualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundoSenhaAtualMouseClicked
       pfSenhaAtual.requestFocus();
    }//GEN-LAST:event_fundoSenhaAtualMouseClicked

    private void fundoNovaSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundoNovaSenhaMouseClicked
        pfNovaSenha.requestFocus();
    }//GEN-LAST:event_fundoNovaSenhaMouseClicked

    private void fundoRepetirSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundoRepetirSenhaMouseClicked
        pfSenhaRepetida.requestFocus();
    }//GEN-LAST:event_fundoRepetirSenhaMouseClicked

    private void btnAltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltMouseClicked
        boolean isOK    = true;
        
        /* PEGA O VALOR DAS NOVAS SENHAS ------------------------------------ */
            String novaSenha   = new String (pfNovaSenha.getPassword());
            String senhaRepeat = new String (pfSenhaRepetida.getPassword());
        /* ------------------------------------------------------------------ */
        
        // VERIFICA SE A SENHA ATUAL CORRESPONDE À ORIGINAL
        if(sqlPadroes.loginIsCorrect("funcionario", this.nomeUsuario, pfSenhaAtual) == false) {
            msg.erro("senha atual", "senha incorreta", pfSenhaAtual);
            isOK = false;}
        
        // VERIFICA SE A NOVA SENHA TEM O TAMANHO DE CARACTERES MÍNIMO (6)
        else if((novaSenha.length() < 6) || (senhaRepeat.length() <6) ) {
            msg.erro("nova senha", "A senha deverá possuir no mínimo 6 caracteres", pfNovaSenha);
            isOK = false;}
        
        // VERIFICA SE AS NOVAS SENHAS CORRESPONDEM
        else if(!senhaRepeat.equals(novaSenha)) {
            msg.erro("nova senha", "OS valores não correspondem", pfNovaSenha);
            pfSenhaRepetida.setText("");
            isOK = false;}
        
        
        // SE ESTIVER TUDO OK SERÁ EFETUADO O CADASTRO
        if(isOK == true) {
            
            // ALTERA A SENHA NO BANCO DE DADOS...
                this.db.SQLExecute("UPDATE funcionario SET Senha = '"+novaSenha+"' WHERE (Usuario LIKE '"+this.nomeUsuario+"')");
            
            // EXIBE A MENSAGEM DE INSERÇÃO CONCUÍDA
            msg.successfullyRegistered("Senha alterada");
            this.dispose();
        }
    }//GEN-LAST:event_btnAltMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel fundoNovaSenha;
    private javax.swing.JLabel fundoRepetirSenha;
    private javax.swing.JLabel fundoSenhaAtual;
    private javax.swing.JLabel iconTitulo;
    private javax.swing.JLabel imgBorda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pfNovaSenha;
    private javax.swing.JPasswordField pfSenhaAtual;
    private javax.swing.JPasswordField pfSenhaRepetida;
    private javax.swing.JPanel pnLateralMenu;
    private javax.swing.JPanel pnlCampos;
    private javax.swing.JPanel pnlLateral;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JSeparator sepCampos;
    private javax.swing.JSeparator sepLogo;
    private javax.swing.JSeparator sepTitulo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtNovaSenha;
    private javax.swing.JLabel txtRepetirSenha;
    private javax.swing.JLabel txtSenhaAtual;
    private javax.swing.JLabel txtTituloEmpresa;
    // End of variables declaration//GEN-END:variables
}
