/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import Padroes.Mensagens_Prontas;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author samuel
 */
public class ShowSobre extends javax.swing.JDialog {

    private Mensagens_Prontas msg;
    
    public ShowSobre() {
        initComponents();
        
        this.msg = new Mensagens_Prontas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        iconLogo = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JLabel();
        txtVersao = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        txtPgCriador = new javax.swing.JLabel();
        txtPgCriadorLink = new javax.swing.JLabel();
        txtYF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlFundo.setBackground(new java.awt.Color(17, 32, 63));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LOGO.png"))); // NOI18N

        txtNome.setFont(new java.awt.Font("Agency FB", 1, 50)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNome.setText("PSC LAVA-JATO");

        txtDescricao.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(153, 153, 153));
        txtDescricao.setText("Sistema de lava-jato desenvolvido em Java 8");

        txtVersao.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtVersao.setForeground(new java.awt.Color(255, 255, 255));
        txtVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtVersao.setText("Versão 1.4.0.0 ");

        btnFechar.setBackground(new java.awt.Color(204, 204, 204));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(0, 0, 0));
        btnFechar.setText("FECHAR");
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
        });

        txtPgCriador.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        txtPgCriador.setForeground(new java.awt.Color(153, 153, 153));
        txtPgCriador.setText("Visite a página do desenvolvedor no github: ");

        txtPgCriadorLink.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        txtPgCriadorLink.setText("<html><a style=\"color: #ffffff;\" href=\"https://github.com/SamuelMTeixeira\">github.com/SamuelMTeixeira</a><html>");
        txtPgCriadorLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPgCriadorLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPgCriadorLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPgCriadorLinkMouseExited(evt);
            }
        });

        txtYF.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        txtYF.setForeground(new java.awt.Color(153, 153, 153));
        txtYF.setText("Instituto Federal do Norte de Minas Gerais - 4º semestre - 2022");

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVersao)
                        .addGap(63, 63, 63))))
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(txtPgCriador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPgCriadorLink)))
                .addContainerGap())
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVersao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtYF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPgCriador)
                    .addComponent(txtPgCriadorLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnFecharMouseClicked

    private void txtPgCriadorLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPgCriadorLinkMouseClicked
        try{
            Desktop.getDesktop().browse(new URI("https://github.com/SamuelMTeixeira"));
        }catch(Exception erro){
            this.msg.texto("erro");
        }
    }//GEN-LAST:event_txtPgCriadorLinkMouseClicked

    private void txtPgCriadorLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPgCriadorLinkMouseEntered
        txtPgCriadorLink.setText("<html><a style='color: #528B8B;' href='https://github.com/SamuelMTeixeira\'>github.com/SamuelMTeixeira</a><html>");
    }//GEN-LAST:event_txtPgCriadorLinkMouseEntered

    private void txtPgCriadorLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPgCriadorLinkMouseExited
        txtPgCriadorLink.setText("<html><a style='color: #ffffff;' href='https://github.com/SamuelMTeixeira\'>github.com/SamuelMTeixeira</a><html>");
    }//GEN-LAST:event_txtPgCriadorLinkMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JLabel txtDescricao;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtPgCriador;
    private javax.swing.JLabel txtPgCriadorLink;
    private javax.swing.JLabel txtVersao;
    private javax.swing.JLabel txtYF;
    // End of variables declaration//GEN-END:variables
}
